# Generated by Django 5.2.4 on 2025-11-20 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('clients', '0002_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Hotel asociado al cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.hotel'),
        ),
    ]
