# Generated by Django 5.2.4 on 2025-09-16 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Imagen de la habitación', upload_to='rooms/')),
                ('alt_text', models.CharField(blank=True, help_text='Texto alternativo para la imagen', max_length=200)),
                ('is_main', models.BooleanField(default=False, help_text='Imagen principal de la habitación')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Imagen de Habitación',
                'verbose_name_plural': 'Imágenes de Habitaciones',
                'ordering': ['-is_main', 'order', 'id'],
            },
        ),
    ]
