# Generated by Django 5.2.4 on 2025-11-20 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('rooms', '0002_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Hotel al que pertenece', null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(help_text='Número de habitación', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('hotel', 'number'), name='uniq_room_hotel_number'),
        ),
    ]
