# Generated by Django 5.2.4 on 2025-09-16 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('nueva_reserva', 'Nueva Reserva'), ('nuevo_cliente', 'Nuevo Cliente'), ('gestionar_habitaciones', 'Gestionar Habitaciones'), ('ver_reportes', 'Ver Reportes'), ('dashboard_view', 'Vista Dashboard')], max_length=50, verbose_name='Acción')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Acción',
                'verbose_name_plural': 'Logs de Acciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
