# Generated by Django 5.2.4 on 2025-11-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
